meta_product_name: "Art Dialogue"
meta_title: "Art Dialogue - Forums of discution about art"
meta_description: "Discuss and debate about movies, books, tv shows, albums"
meta_image: "cover.png" # should exist in `app/assets/images/`
